name: Test

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php_version: [8.0, 8.1, 8.2]
        laravel_version: [8.*, 9.*, 10.*]
        exclude:
          - laravel_version: 8.*
            php_version: 8.1
          - laravel_version: 8.*
            php_version: 8.2
          - laravel_version: 9.*
            php_version: 8.2
          - laravel_version: 10.*
            php_version: 8.0
            
    name: PHP ${{ matrix.php_version }} - Laravel ${{ matrix.laravel_version }}

    steps:
      - name: Checkout commit
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php_version }}

      - name: Validate composer.json
        run: composer validate
      
      - name: Run composer install
        run: composer install --no-interaction --no-suggest
      
      - name: Install Laravel
        run: composer update --no-interaction illuminate/database:^${{ matrix.laravel_version }}

      - name: Run PHPUnit
        run: ./vendor/bin/phpunit
